### PR TITLE
Resolves Example file(s) missing sensor/library name

### PR DESCRIPTION
**Pull request by BiffoBear**
Renamed 'tap_detection.py' to 'lsm303_accel_tap_detection.py'

No other changes.

### CODE REVIEW

**Review by FoamyGuy — APPROVED** [review]
@BiffoBear Thanks for jumping in and helping out with the Library Infrastructure Issues!

**Review by FoamyGuy — CHANGES_REQUESTED** [review]
@BiffoBear It looks like you've made a copy of the `tap_detection.py` file with the new proper name of `lsm303_accel_tap_detection.py` but also left the original `tap_detection.py` file in place. Can you please remove `tap_detection.py` and push again? You should see 4 files in the `examples/` folder and they should all start with `lsm303_accel`

**Comment by BiffoBear** [comment]
Thanks for the quick review. The offending file has been deleted, and I've learned something along the way.

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thanks!

**Pull request merged**
